# -*- coding: utf-8 -*-
"""NUR AZIZAHH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R0-TYDkAyd2tUT2-D8Us34P1_-7BzZRI

## **BOOSTING**
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

df = pd.read_csv('adult.csv')
df
X = df.drop(['occupation','fnlwgt','gender','educational-num','race','income','relationship','marital-status', 'education', 'native-country','workclass'], axis=1)
y = df['capital-gain']

df

X_train, X_test, y_train, y_test = train_test_split(X, y,  test_size=0.2, random_state=42)
y_train = y_train.values.reshape(-1, 1)

base_model2 = DecisionTreeClassifier(max_depth=1)

print(X_train)

print(y_train)

print(y_test)

print(X_test)

boosting_model = AdaBoostClassifier(base_model2, n_estimators=1, random_state=1)

boosting_model.fit(X_train, y_train)

y_pred = boosting_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
akurasi = accuracy*100
print(f"Accuracy: {akurasi:.2f} %")